[package]
name = "ps88"
version.workspace = true
edition.workspace = true
authors = ["Taiki Yoshii"]
license = "GPL-3.0"

keywords = ["synthesizer", "clap", "vst3"]
description = "A programmable synthesizer"
repository = "https://github.com/wakewakame/ps88"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
roboto-mono = { workspace = true }
material-design-icons = { workspace = true }
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "28b149ec4d62757d0b448809148a0c3ca6e09a95", features = ["assert_process_allocs", "standalone"] }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "28b149ec4d62757d0b448809148a0c3ca6e09a95", default-features = false, features = ["opengl"] }
serde = { version = "1", features = ["derive"] }
deno_core = "0.355.0"
thiserror = "2.0.9"
rfd = "0.15.1"
notify = "7.0.0"
log = "0.4.22"
lyon = "1.0.1"

[dev-dependencies]
mockall = "0.13.1"
