[package]
name = "ps88"
version.workspace = true
edition.workspace = true
authors = ["Taiki Yoshii"]
license = "GPL-3.0"

keywords = ["synthesizer", "clap", "vst3"]
description = "A programmable synthesizer"
repository = "https://github.com/wakewakame/ps88"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
roboto-mono = { workspace = true }

nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "16c6c58f4d9f08c9c515c991c218bff235cff6e2", features = ["assert_process_allocs", "standalone"] }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "16c6c58f4d9f08c9c515c991c218bff235cff6e2" }

# deno_core を参照
# https://github.com/denoland/deno_core/blob/f43085b91cd7a6b4ae6ae4efc041bf96bae3961f/Cargo.toml#L23-L31
v8 = { version = "130.0.2", default-features = false }
serde_v8 = "0.236.0"
serde = { version = "1", features = ["derive"] }

thiserror = "2.0.9"
rfd = "0.15.1"
notify = "7.0.0"
log = "0.4.22"
lyon = "1.0.1"

[dev-dependencies]
mockall = "0.13.1"
