[package]
name = "ps88"
version.workspace = true
edition.workspace = true
authors = ["Taiki Yoshii"]
license = "GPL-3.0"

keywords = ["synthesizer", "clap", "vst3"]
description = "A programmable synthesizer"
repository = "https://github.com/wakewakame/ps88"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
roboto-mono = { workspace = true }
material-design-icons = { workspace = true }
egui = { version = "0.35.0", features = ["default_fonts"] }
nice-plug = { git = "https://codeberg.org/RustAudio/nice-plug.git", rev = "42f480568d383632bbcb2f29d0e4349b93566432", features = ["assert_process_allocs", "standalone"] }
nice-plug-egui = { git = "https://codeberg.org/RustAudio/nice-plug.git", rev = "42f480568d383632bbcb2f29d0e4349b93566432", default-features = false, features = ["opengl"] }
serde = { version = "1", features = ["derive"] }
deno_core = "0.355.0"
thiserror = "2.0.9"
rfd = "0.15.1"
notify = "7.0.0"
log = "0.4.22"
lyon = "1.0.1"
arboard = "3.5.0"

[dev-dependencies]
mockall = "0.13.1"
