[env]
# 以下は Linux では rusty_v8 を crate-type = ["cdylib"] としてビルドできない問題を回避するための指定
# https://github.com/denoland/rusty_v8/issues/1706
# https://github.com/denoland/rusty_v8/issues/1798
V8_FROM_SOURCE = "1"
PRINT_GN_ARGS = "1"
GN_ARGS = "v8_monolithic=true v8_monolithic_for_shared_library=true"
